spring.application.name: vote-stream
spring.cloud.stream.bindings.process-in-0:
  destination: votes
spring.cloud.stream.bindings.process-out-0:
  destination: votes-by-survey
spring.cloud.stream.kafka.streams.binder:
  configuration:
    default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde

