// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Vote struct {
	ID      string  `json:"id"`
	Option  int     `json:"option"`
	Name    string  `json:"name"`
	Message *string `json:"message"`
}
